### PR TITLE
added lower bound to make code compile in Eclipse

### PR DESCRIPTION
**Pull request by joergreichert**

### CODE REVIEW

**Comment by sepe81** [comment]
I also compile this under eclipse and Java 8 without any problems. Are you using the gradle build? You can generate the eclipse projekt with `gradlew eclipse`

**Comment by joergreichert** [comment]
I used Maven and mvn eclipse:eclipse. But I give Gradle a try.

**Comment by sepe81** [comment]
@joergreichert I tried to fix/update the maven build with 6ce8915d675667198a75b9f447367cd17c69ac9a. Most likely the compiler problems came from wrong java version settings. We depend on Java 8 but the pom declared Java 7. Could you please try again?

**Comment by joergreichert** [comment]
Ok, the issue was, that I used mvn eclipse:eclipse but the then manually imported project had no Maven nature assigned. When adding the Maven project nature the compile warning went away.

**Pull request closed without merging**
